#ifndef CONSTANTS_H
#define CONSTANTS_H

#define VERSION std::string("Open Alpha 0.1")
#define IP_ADDRESS sf::IpAddress("174.56.242.113")
#define PORT 51130

#define DISCORD_DETAILS "Adding Character HUD..."

#define FONT "assets/fonts/Lucida Sans.ttf"
#define JA_FONT "assets/fonts/KozGoPro-Regular.otf"

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define MARGIN 30.f //
#define PADDING 10.f //
#define TAB_HEIGHT 20.f
#define MEMBERLIST_WIDTH 100.f
#define TYPEBOX_HEIGHT 50.f

#define CHATBOX_WIDTH   WINDOW_WIDTH - 2 * MARGIN - MEMBERLIST_WIDTH - 2 * PADDING          // 
#define CHATBOX_HEIGHT  WINDOW_HEIGHT - 2 * MARGIN - TYPEBOX_HEIGHT - PADDING
#define TYPEBOX_WIDTH   CHATBOX_WIDTH + MEMBERLIST_WIDTH - TYPEBOX_HEIGHT
#define HUD_HEIGHT 140

#define TEXT_SIZE 13

#define J_STR(x) x + " has joined!"
#define C_STR(x, y) x + " has changed their username to " + y
#define D_STR(x) x + " has disconnected!"

#define GENERAL_CHANNEL Channel("general", "General", Channel::PUBLIC_OOC)
#define NO_CHANNEL(x) Channel("na", "N/A", x)

enum Species
{
  NO_SPECIES,
  BULBASAUR,
  IVYSAUR,
  VENUSAUR,
  CHARMANDER,
  CHARMELEON,
  CHARIZARD,
  SQUIRTLE,
  WARTORTLE,
  BLASTOISE,

  VULPIX = 37,
  NINETALES,

  EEVEE = 133,
  VAPOREON,
  JOLTEON,
  FLAREON,
  PORYGON,

  ARCTICUNO = 144,
  ZAPDOS,
  MOLTRES,

  MEWTWO = 150,
  MEW,

  TOTODILE = 158,
  CROCONAW,
  FERALIGATR,

  ESPEON = 196,
  UMBREON,

  GLIGAR = 207,

  SWINUB = 220,
  PILOSWINE,

  PORYGON2 = 233,

  RAIKOU = 243,
  ENTEI,
  SUICUNE,

  LUGIA = 249,
  HO_OH,
  CELEBI,

  RALTS = 280,
  KIRLIA,
  GARDEVOIR,

  KECLEON = 352,

  REGIROCK = 377,
  REGICE,
  REGISTEEL,
  LATIAS,
  LATIOS,
  KYOGRE,
  GROUDON,
  RAYQUAZA,
  JIRACHI,
  DEOXYS,

  RIOLU = 447,
  LUCARIO,

  LEAFEON = 470,
  GLACEON,
  GLISCOR,
  MAMOSWINE,
  PORYGON_Z,
  GALLADE,

  ROTOM = 479,
  UXIE,
  MESPIRIT,
  AZELF,
  DIALGA,
  PALKIA,
  HEATRAN,
  REGIGIGAS,
  GIRATINA,
  CRESSELIA,
  PHIONE,
  MANAPHY,
  DARKRAI,
  SHAYMIN,
  ARCEUS,
  VICTINI,

  JOLTIK = 595,
  GALVANTULA,

  GOLETT = 622,
  GOLURK,

  COBALION = 638,
  TERRAKION,
  VIRIZION,
  TORNADUS,
  THUNDURUS,
  RESHIRAM,
  ZEKROM,
  LANDORUS,
  KYUREM,
  KELDEO,
  MELOETTA,
  GENESECT,

  SYLVEON = 700,

  XERNEAS = 716,
  YVELTAL,
  ZYGARDE,
  DIANCIE,
  HOOPA,
  VOLCANION,

  TAPU_KOKO = 785,
  TAPU_LELE,
  TAPU_BULU,
  TAPU_FINI,
  COSMOG,
  COSMOEM,
  SOLGALEO,
  LUNALA,
  NIHILEGO,
  BUZZWOLE,
  PHEROMOSA,
  XURKITREE,
  CELESTEELA,
  KARTANA,
  GUZZLORD,
  NECROZMA,
  MAGEARNA,
  MARSHADOW,
  POIPOLE,
  NAGANADEL,
  STAKATAKA,
  BLACEPHALON,
  ZERAORA
};

enum Type
{
  NO_TYPE,
  NORMAL,
  FIRE,
  WATER,
  ELECTRIC,
  GRASS,
  ICE,
  FIGHTING,
  POISON,
  GROUND,
  FLYING,
  PSYCHIC,
  BUG,
  ROCK,
  GHOST,
  DRAGON,
  DARK,
  STEEL,
  FAIRY,

  TYPE_COUNT
};

#define NORMAL_COLOR sf::Color(0xA8, 0xA8, 0x78)
#define FIRE_COLOR sf::Color(0xF0, 0x80, 0x30)
#define WATER_COLOR sf::Color(0x68, 0x90, 0xF0)
#define ELECTRIC_COLOR sf::Color(0xF8, 0xD0, 0x30)
#define GRASS_COLOR sf::Color(0x78, 0xC8, 0x50)
#define ICE_COLOR sf::Color(0x98, 0xD8, 0xD8)
#define FIGHTING_COLOR sf::Color(0xC0, 0x30, 0x28)
#define POISON_COLOR sf::Color(0xA0, 0x40, 0xA0)
#define GROUND_COLOR sf::Color(0xE0, 0xC0, 0x68)
#define FLYING_COLOR sf::Color(0xA8, 0x90, 0xF0)
#define PSYCHIC_COLOR sf::Color(0xF8, 0x58, 0x88)
#define BUG_COLOR sf::Color(0xA8, 0xB8, 0x20)
#define ROCK_COLOR sf::Color(0xB8, 0xA0, 0x38)
#define GHOST_COLOR sf::Color(0x70, 0x58, 0x98)
#define DRAGON_COLOR sf::Color(0x70, 0x38, 0xF8)
#define DARK_COLOR sf::Color(0x70, 0x58, 0x48)
#define STEEL_COLOR sf::Color(0xB8, 0xB8, 0xD0)
#define FAIRY_COLOR sf::Color(0xEE, 0x99, 0xAC)

enum Status
{
  BLEED,
  BURN,
  SLEEP,
  POISON_STATUS,
  BAD_POISON,

  ENTANGLE,
  FLINCH,
  FREEZE,
  PARALYZE,
  SCARE,
  TERRIFY,

  CONFUSE,
  STAGGER,
  FAINT,

  STATUS_COUNT
};

#endif
